/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, useGLTF } from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas } from '@react-three/fiber'

export function WinterV3() {
    const { nodes, materials } = useGLTF('./models/Winter/WinterV3.glb')

    return (
        <Canvas
            flat
            camera={{
                fov: 45,
                near: 0.1,
                far: 200,
                position: [2, 1, 2],
            }}
        >
            <color args={['#ffffff']} attach="background" />
            <OrbitControls makeDefault />
            <Perf />
            <ambientLight />
            <directionalLight intensity={2} castShadow position={[2, 2, 2]} />
            <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush1001.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.208, 0.623, -0.839]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2004.geometry}
                    material={materials.BushesWinter}
                    position={[0.423, 0.666, -0.685]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2005.geometry}
                    material={materials.BushesWinter}
                    position={[0.829, 0.633, -0.236]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2006.geometry}
                    material={materials.BushesWinter}
                    position={[-0.541, 0.61, 0.717]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2007.geometry}
                    material={materials.BushesWinter}
                    position={[-0.871, 0.616, 0.325]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3002.geometry}
                    material={materials.BushesWinter}
                    position={[0.909, 0.605, -0.046]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3003.geometry}
                    material={materials.BushesWinter}
                    position={[0.7, 0.605, -0.576]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush4001.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.69, 0.623, 0.489]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5003.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.555, 0.582, 0.661]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5004.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.823, 0.582, -0.429]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5005.geometry}
                    material={materials.BushesDarkWinter}
                    position={[-0.687, 0.593, 0.615]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Big_tree002.geometry}
                    material={materials.TrunkWinter}
                    position={[0.411, 0.816, -0.401]}
                />
                <group position={[0.444, 1.233, -0.197]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh003.geometry}
                        material={materials.Snow}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh003_1.geometry}
                        material={materials.Snow}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock1.geometry}
                    material={materials.Stone}
                    position={[-0.382, 0.559, 0.929]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock2.geometry}
                    material={materials.Stone}
                    position={[-0.852, 0.527, -0.336]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock3.geometry}
                    material={materials.Stone}
                    position={[0.316, 0.539, 0.82]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock4.geometry}
                    material={materials.Stone}
                    position={[-0.747, 0.541, -0.323]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock5.geometry}
                    material={materials.Stone}
                    position={[-0.263, 0.531, -0.662]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock6.geometry}
                    material={materials.Stone}
                    position={[-0.007, 0.512, 0.197]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock7.geometry}
                    material={materials.Stone}
                    position={[-0.445, 0.541, -0.932]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock8.geometry}
                    material={materials.Stone}
                    position={[0.303, 0.562, 0.938]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock9.geometry}
                    material={materials.Stone}
                    position={[-0.606, 0.531, 0.006]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock10.geometry}
                    material={materials.Stone}
                    position={[-0.034, 0.514, 0.123]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock11.geometry}
                    material={materials.Stone}
                    position={[-0.877, 0.531, -0.421]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock12.geometry}
                    material={materials.Stone}
                    position={[-0.676, 0.534, -0.057]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock13.geometry}
                    material={materials.Stone}
                    position={[-0.229, 0.56, -0.57]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock14.geometry}
                    material={materials.Stone}
                    position={[-0.187, 0.538, -0.455]}
                />
                <group position={[-0.31, 0.581, 0.004]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh015.geometry}
                        material={materials.Snow}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh015_1.geometry}
                        material={materials.Stone}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.River_plane001.geometry}
                    material={materials.Water}
                    position={[-0.251, 0.508, 0.127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['Ground-winter001'].geometry}
                    material={materials.Dirt}
                    position={[0.005, 0.33, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowLeft.geometry}
                    material={materials.Snow}
                    position={[0.005, 0.164, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowRight.geometry}
                    material={materials.Snow}
                    position={[0.005, 0.284, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush.geometry}
                    material={materials.Snow}
                    position={[0.577, 0.735, 0.476]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush001.geometry}
                    material={materials.Snow}
                    position={[0.712, 0.683, -0.573]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush002.geometry}
                    material={materials.Snow}
                    position={[-0.537, 0.68, 0.722]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush003.geometry}
                    material={materials.Snow}
                    position={[-0.684, 0.675, 0.61]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush004.geometry}
                    material={materials.Snow}
                    position={[0.211, 0.751, -0.859]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush005.geometry}
                    material={materials.Snow}
                    position={[0.454, 0.805, -0.7]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush006.geometry}
                    material={materials.Snow}
                    position={[0.859, 0.707, -0.054]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush007.geometry}
                    material={materials.Snow}
                    position={[0.817, 0.733, -0.252]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush008.geometry}
                    material={materials.Snow}
                    position={[0.563, 0.659, 0.672]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush1.geometry}
                    material={materials.Snow}
                    position={[-0.866, 0.713, 0.326]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush1001.geometry}
                    material={materials.Snow}
                    position={[0.832, 0.654, -0.428]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry.geometry}
                    material={materials.Berry}
                    position={[0.623, 0.795, 0.47]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry001.geometry}
                    material={materials.Berry}
                    position={[0.723, 0.768, 0.395]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry002.geometry}
                    material={materials.Berry}
                    position={[0.801, 0.768, 0.499]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry003.geometry}
                    material={materials.Berry}
                    position={[0.689, 0.766, 0.609]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry004.geometry}
                    material={materials.Berry}
                    position={[0.845, 0.806, -0.154]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry005.geometry}
                    material={materials.Berry}
                    position={[0.744, 0.817, -0.229]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry006.geometry}
                    material={materials.Berry}
                    position={[0.818, 0.815, -0.335]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry007.geometry}
                    material={materials.Berry}
                    position={[0.943, 0.77, -0.264]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry008.geometry}
                    material={materials.Berry}
                    position={[-0.809, 0.762, 0.395]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry009.geometry}
                    material={materials.Berry}
                    position={[-0.97, 0.745, 0.353]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry010.geometry}
                    material={materials.Berry}
                    position={[-0.93, 0.753, 0.233]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry011.geometry}
                    material={materials.Berry}
                    position={[-0.822, 0.77, 0.258]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry012.geometry}
                    material={materials.Berry}
                    position={[-0.899, 0.749, 0.43]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry013.geometry}
                    material={materials.Berry}
                    position={[0.506, 0.902, -0.641]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry014.geometry}
                    material={materials.Berry}
                    position={[0.344, 0.892, -0.683]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry015.geometry}
                    material={materials.Berry}
                    position={[0.385, 0.863, -0.803]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry016.geometry}
                    material={materials.Berry}
                    position={[0.493, 0.881, -0.777]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Berry017.geometry}
                    material={materials.Berry}
                    position={[0.415, 0.9, -0.605]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowmanBottom.geometry}
                    material={materials.Snow}
                    position={[0.492, 0.739, 0.023]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowmanHead.geometry}
                    material={materials.Snow}
                    position={[0.492, 0.868, 0.023]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Hat001.geometry}
                    material={materials.Hat}
                    position={[0.511, 0.941, 0.025]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.LeftEye.geometry}
                    material={materials.Coal}
                    position={[0.434, 0.887, -0.007]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RightEye.geometry}
                    material={materials.Coal}
                    position={[0.428, 0.887, 0.036]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Nose.geometry}
                    material={materials.Carrot}
                    position={[0.398, 0.869, 0.015]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Scarf.geometry}
                    material={materials.Hat}
                    position={[0.465, 0.83, 0.032]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.RightHand.geometry}
                    material={materials.Trunk}
                    position={[0.469, 0.813, -0.103]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.LeftHand.geometry}
                    material={materials.Trunk}
                    position={[0.469, 0.813, 0.161]}
                />
            </group>
        </Canvas>
    )
}

useGLTF.preload('./models/Winter/WinterV3.glb')
