/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, useGLTF, useTexture } from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas } from '@react-three/fiber'

export function SakuraScene(props) {
    const { nodes } = useGLTF('./models/bakedSpring/Spring.glb')
    const bakedTexture = useTexture('./models/bakedSpring/baked.jpg')
    // eslint-disable-next-line
    bakedTexture.flipY = false

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.merged.geometry}
                position={[-1.255, 0.616, 0.493]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
            <mesh
                geometry={nodes.River.geometry}
                position={[-0.635, 0.508, 0.294]}
            >
                <meshBasicMaterial />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/bakedSpring/Spring.glb')

export function SakuraSceneBaked() {
    return (
        <Canvas gl={{ stencil: true }}>
            <color args={['#291b18']} attach="background" />
            <OrbitControls makeDefault />
            <Perf />
            <SakuraScene />
        </Canvas>
    )
}
