/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from '@react-three/drei'

import { useStencil } from './utils/stencilBuffer'
import { SEASONS } from './store/useSceneState'

export function Boat(props) {
    const stencil = useStencil(SEASONS.spring)

    const { nodes } = useGLTF('./models/Boat/boatMerged.glb')
    const bakedTexture = useTexture('./models/Boat/baked.png')

    // eslint-disable-next-line
    bakedTexture.flipY = false

    return (
        <group dispose={null} {...props}>
            <mesh
                geometry={nodes.boat.geometry}
                position={[0.068, 0.521, 0.603]}
            >
                <meshBasicMaterial map={bakedTexture} {...stencil} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Boat/boatMerged.glb')
useTexture.preload('./models/Boat/baked.png')
