/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Boat(props) {
    const { nodes, materials } = useGLTF('./models/Boat/boat-row-small.glb')

    return (
        <group
            scale={0.2}
            // Same Y as river
            position={[0, 0.508, 0.75]}
            rotation={[0, 3, 0]}
            dispose={null}
            {...props}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['boat-row-small_1'].geometry}
                material={materials.colormap}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.paddles.geometry}
                    material={materials.colormap}
                    position={[0, 0.056, -0.175]}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Boat/boat-row-small.glb')