/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function CorkModel(props) {
    const { nodes, materials } = useGLTF('./models/Cork/Cork.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cork.geometry}
                material={materials.Cork}
                position={[-0.023, 2.426, 0.011]}
                scale={0.99}
            />
        </group>
    )
}

useGLTF.preload('./models/Cork/Cork.glb')
