/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from '@react-three/drei'

export function CorkModel(props) {
    const { nodes } = useGLTF('./models/Cork/Cork.glb')
    const bakedTexture = useTexture('./models/Cork/baked.jpg')

    // eslint-disable-next-line
    bakedTexture.flipY = false

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cork.geometry}
                position={[-0.023, 2.426, 0.011]}
                scale={0.99}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Cork/Cork.glb')
useTexture.preload('./models/Cork/baked.jpg')
