/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useTexture } from '@react-three/drei'

export function Rope(props) {
    const { nodes } = useGLTF('./models/Rope/RopeAndRing.glb')
    const bakedRopeTexture = useTexture('./models/Rope/baked_compressed.jpg')

    const ringMatcap = useTexture('./textures/bronzeMatcap/matcap.png')

    // eslint-disable-next-line
    bakedRopeTexture.flipY = false

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Rope002.geometry}
                position={[-0.025, 2.217, 0.008]}
                rotation={[0, 1.329, 0]}
                scale={0.022}
            >
                <meshBasicMaterial map={bakedRopeTexture} />
            </mesh>
            <mesh
                geometry={nodes.Rope001.geometry}
                position={[-0.025, 2.293, 0.008]}
                rotation={[-Math.PI, 0.026, -Math.PI]}
                scale={0.022}
            >
                <meshBasicMaterial map={bakedRopeTexture} />
            </mesh>
            <mesh
                geometry={nodes.Ring.geometry}
                position={[0.009, 2.246, 0.495]}
                rotation={[0, 0, -1.638]}
                scale={[0.089, 0.128, 0.082]}
            >
                <meshMatcapMaterial matcap={ringMatcap} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Rope/RopeAndRing.glb')
useTexture.preload('./models/Rope/baked_compressed.jpg')
useTexture.preload('./textures/bronzeMatcap/matcap.png')
