/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, useGLTF, useTexture } from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas } from '@react-three/fiber'

export function WinterScene() {
    const { nodes } = useGLTF('./models/Winter/WinterMerged.glb')
    const bakedTexture = useTexture('./models/Winter/BakedWinter.jpg')
    // eslint-disable-next-line
    bakedTexture.flipY = false

    return (
        <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.river001.geometry}
                position={[-0.251, 0.508, 0.127]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.snow.geometry}
                position={[0.005, 0.284, -0.003]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.merged001.geometry}
                position={[0.385, 0.863, -0.803]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Winter/WinterMerged.glb')

export function WinterSceneBaked() {
    return (
        <Canvas
            flat
            camera={{
                fov: 45,
                near: 0.1,
                far: 200,
                position: [2, 1, 2],
            }}
        >
            <color args={['#291b18']} attach="background" />
            <OrbitControls makeDefault />
            <Perf />
            <WinterScene />
        </Canvas>
    )
}
