/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, useGLTF } from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas } from '@react-three/fiber'

export function WinterV1() {
    const { nodes, materials } = useGLTF('./models/Winter/WinterV1.glb')
    return (
        <Canvas
            flat
            camera={{
                fov: 45,
                near: 0.1,
                far: 200,
                position: [2, 1, 2],
            }}
        >
            <color args={['#ffffff']} attach="background" />
            <OrbitControls makeDefault />
            <Perf />
            <ambientLight />
            <directionalLight />
            <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.River_plane001.geometry}
                    material={materials.Water}
                    position={[-0.251, 0.508, 0.127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['Ground-winter001'].geometry}
                    material={materials.Dirt}
                    position={[0.005, 0.33, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SNOW_RIGHT_FINAL.geometry}
                    material={materials.Snow}
                    position={[0.005, 0.284, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SNOW_LEFT_FINAL.geometry}
                    material={materials.Snow}
                    position={[0.005, 0.164, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush1001.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.208, 0.623, -0.839]}
                    rotation={[-0.447, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2004.geometry}
                    material={materials.BushesWinter}
                    position={[0.423, 0.666, -0.685]}
                    rotation={[-0.204, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2005.geometry}
                    material={materials.Bushes}
                    position={[0.829, 0.633, -0.236]}
                    rotation={[-0.128, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2006.geometry}
                    material={materials.BushesWinter}
                    position={[-0.541, 0.61, 0.717]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2007.geometry}
                    material={materials.BushesDarkWinter}
                    position={[-0.871, 0.616, 0.325]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3002.geometry}
                    material={materials.Bushes}
                    position={[0.909, 0.605, -0.046]}
                    rotation={[-0.061, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3003.geometry}
                    material={materials.Bushes}
                    position={[0.7, 0.605, -0.576]}
                    rotation={[-0.146, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush4001.geometry}
                    material={materials.BushesWinter}
                    position={[0.69, 0.623, 0.489]}
                    rotation={[0, 0, -0.158]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5003.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.555, 0.582, 0.661]}
                    rotation={[0, 0, -0.179]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5004.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.823, 0.582, -0.429]}
                    rotation={[-0.082, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5005.geometry}
                    material={materials.BushesDarkWinter}
                    position={[-0.687, 0.593, 0.615]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Big_tree002.geometry}
                    material={materials.TrunkWinter}
                    position={[0.411, 0.816, -0.401]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001.geometry}
                    material={materials.Stone}
                    position={[-0.382, 0.559, 0.929]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003.geometry}
                    material={materials.Stone}
                    position={[-0.852, 0.527, -0.336]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004.geometry}
                    material={materials.Stone}
                    position={[0.316, 0.539, 0.82]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube007.geometry}
                    material={materials.Stone}
                    position={[-0.747, 0.541, -0.323]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube017.geometry}
                    material={materials.Stone}
                    position={[-0.263, 0.531, -0.662]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube018.geometry}
                    material={materials.Stone}
                    position={[-0.007, 0.512, 0.197]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube025.geometry}
                    material={materials.Stone}
                    position={[-0.445, 0.541, -0.932]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube026.geometry}
                    material={materials.Stone}
                    position={[0.303, 0.562, 0.938]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube027.geometry}
                    material={materials.Stone}
                    position={[-0.606, 0.531, 0.006]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube028.geometry}
                    material={materials.Stone}
                    position={[-0.034, 0.514, 0.123]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube029.geometry}
                    material={materials.Stone}
                    position={[-0.877, 0.531, -0.421]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube030.geometry}
                    material={materials.Stone}
                    position={[-0.676, 0.534, -0.057]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube031.geometry}
                    material={materials.Stone}
                    position={[-0.229, 0.56, -0.57]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube032.geometry}
                    material={materials.Stone}
                    position={[-0.187, 0.538, -0.455]}
                />
            </group>
        </Canvas>
    )
}

useGLTF.preload('./models/Winter/WinterV1.glb')
