/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function Terrain(props) {
    const { nodes } = useGLTF('./models/Spring/Terrain.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.GrassPlane.geometry}
                position={[0.005, 0.33, -0.003]}
            >
                <meshBasicMaterial color="#6f8f46" />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Spring/Terrain.glb')
