/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, useGLTF } from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas } from '@react-three/fiber'

export function WinterV2() {
    const { nodes, materials } = useGLTF('./models/Winter/WinterV2.glb')
    return (
        <Canvas
            flat
            camera={{
                fov: 45,
                near: 0.1,
                far: 200,
                position: [2, 1, 2],
            }}
        >
            <color args={['#ffffff']} attach="background" />
            <OrbitControls makeDefault />
            <Perf />
            <ambientLight />
            <directionalLight />
            <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush1001.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.208, 0.623, -0.839]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2004.geometry}
                    material={materials.BushesWinter}
                    position={[0.423, 0.666, -0.685]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2005.geometry}
                    material={materials.Bushes}
                    position={[0.829, 0.633, -0.236]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2006.geometry}
                    material={materials.BushesWinter}
                    position={[-0.541, 0.61, 0.717]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2007.geometry}
                    material={materials.BushesDarkWinter}
                    position={[-0.871, 0.616, 0.325]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3002.geometry}
                    material={materials.Bushes}
                    position={[0.909, 0.605, -0.046]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3003.geometry}
                    material={materials.Bushes}
                    position={[0.7, 0.605, -0.576]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush4001.geometry}
                    material={materials.BushesWinter}
                    position={[0.69, 0.623, 0.489]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5003.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.555, 0.582, 0.661]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5004.geometry}
                    material={materials.BushesDarkWinter}
                    position={[0.823, 0.582, -0.429]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5005.geometry}
                    material={materials.BushesDarkWinter}
                    position={[-0.687, 0.593, 0.615]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Big_tree002.geometry}
                    material={materials.TrunkWinter}
                    position={[0.411, 0.816, -0.401]}
                />
                <group position={[0.444, 1.233, -0.197]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh003.geometry}
                        material={materials.Snow}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh003_1.geometry}
                        material={nodes.Mesh003_1.material}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock1.geometry}
                    material={materials.Stone}
                    position={[-0.382, 0.559, 0.929]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock2.geometry}
                    material={materials.Stone}
                    position={[-0.852, 0.527, -0.336]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock3.geometry}
                    material={materials.Stone}
                    position={[0.316, 0.539, 0.82]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock4.geometry}
                    material={materials.Stone}
                    position={[-0.747, 0.541, -0.323]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock5.geometry}
                    material={materials.Stone}
                    position={[-0.263, 0.531, -0.662]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock6.geometry}
                    material={materials.Stone}
                    position={[-0.007, 0.512, 0.197]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock7.geometry}
                    material={materials.Stone}
                    position={[-0.445, 0.541, -0.932]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock8.geometry}
                    material={materials.Stone}
                    position={[0.303, 0.562, 0.938]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock9.geometry}
                    material={materials.Stone}
                    position={[-0.606, 0.531, 0.006]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock10.geometry}
                    material={materials.Stone}
                    position={[-0.034, 0.514, 0.123]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock11.geometry}
                    material={materials.Stone}
                    position={[-0.877, 0.531, -0.421]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock12.geometry}
                    material={materials.Stone}
                    position={[-0.676, 0.534, -0.057]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock13.geometry}
                    material={materials.Stone}
                    position={[-0.229, 0.56, -0.57]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.rock14.geometry}
                    material={materials.Stone}
                    position={[-0.187, 0.538, -0.455]}
                />
                <group position={[-0.31, 0.581, 0.004]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh015.geometry}
                        material={materials.Snow}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh015_1.geometry}
                        material={materials.Stone}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.River_plane001.geometry}
                    material={materials.Water}
                    position={[-0.251, 0.508, 0.127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['Ground-winter001'].geometry}
                    material={materials.Dirt}
                    position={[0.005, 0.33, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowLeft.geometry}
                    material={materials.Snow}
                    position={[0.005, 0.164, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowRight.geometry}
                    material={materials.Snow}
                    position={[0.005, 0.284, -0.003]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush.geometry}
                    material={materials.Snow}
                    position={[0.577, 0.735, 0.476]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush001.geometry}
                    material={materials.Snow}
                    position={[0.712, 0.683, -0.573]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush002.geometry}
                    material={materials.Snow}
                    position={[-0.537, 0.68, 0.722]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush003.geometry}
                    material={materials.Snow}
                    position={[-0.684, 0.675, 0.61]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush004.geometry}
                    material={materials.Snow}
                    position={[0.211, 0.751, -0.859]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush005.geometry}
                    material={materials.Snow}
                    position={[0.454, 0.805, -0.7]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush006.geometry}
                    material={materials.Snow}
                    position={[0.859, 0.707, -0.054]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush007.geometry}
                    material={materials.Snow}
                    position={[0.817, 0.733, -0.252]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush008.geometry}
                    material={materials.Snow}
                    position={[0.563, 0.659, 0.672]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush1.geometry}
                    material={materials.Snow}
                    position={[-0.866, 0.713, 0.326]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.SnowOnBush1001.geometry}
                    material={materials.Snow}
                    position={[0.832, 0.654, -0.428]}
                />
            </group>
        </Canvas>
    )
}

useGLTF.preload('./models/Winter/WinterV2.glb')
