/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, useGLTF } from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas } from '@react-three/fiber'

export function SakuraScene() {
    const { nodes, materials } = useGLTF('./models/Sakura_scene_full.glb')
    return (
        <Canvas
            flat
            camera={{
                fov: 45,
                near: 0.1,
                far: 200,
                position: [2, 1, 2],
            }}
        >
            <color args={['#ffffff']} attach="background" />
            <OrbitControls makeDefault />
            <Perf />
            <ambientLight />
            <directionalLight />
            <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['Ground-spring'].geometry}
                    material={materials.Grass}
                    position={[-0.38, 0.33, 0.164]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Big_tree001.geometry}
                    material={materials.Trunk}
                    position={[0.027, 0.816, -0.234]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[0.022, 1.38, 0.138]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere001.geometry}
                    material={materials['spring-leaves']}
                    position={[0.063, 1.352, -0.637]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere002.geometry}
                    material={materials['spring-leaves']}
                    position={[0.147, 1.494, -0.265]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere003.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[-0.123, 1.212, -0.205]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere004.geometry}
                    material={materials['spring-leaves']}
                    position={[0.11, 1.39, -0.02]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere005.geometry}
                    material={materials['spring-leaves']}
                    position={[0.038, 1.408, -0.371]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere006.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[0.082, 1.443, -0.139]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere007.geometry}
                    material={materials['spring-leaves']}
                    position={[-0.091, 1.214, -0.269]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere008.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[0.042, 1.349, -0.53]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere009.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[0.037, 1.271, -0.45]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere010.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[-0.001, 1.306, -0.397]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere011.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[0.025, 1.205, -0.222]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere012.geometry}
                    material={materials['spring-leaves-dark']}
                    position={[0.126, 1.317, 0.013]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush1.geometry}
                    material={materials.Bushes_dark}
                    position={[-0.177, 0.623, -0.671]}
                    rotation={[-0.447, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2.geometry}
                    material={materials.Bushes}
                    position={[0.039, 0.666, -0.518]}
                    rotation={[-0.204, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3.geometry}
                    material={materials.Bushes}
                    position={[0.525, 0.605, 0.121]}
                    rotation={[-0.061, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush4.geometry}
                    material={materials.Bushes}
                    position={[0.306, 0.623, 0.656]}
                    rotation={[0, 0, -0.158]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5.geometry}
                    material={materials.Bushes_dark}
                    position={[0.171, 0.582, 0.828]}
                    rotation={[0, 0, -0.179]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2001.geometry}
                    material={materials.Bushes}
                    position={[0.444, 0.633, -0.069]}
                    rotation={[-0.128, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5001.geometry}
                    material={materials.Bushes_dark}
                    position={[0.438, 0.582, -0.262]}
                    rotation={[-0.082, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush3001.geometry}
                    material={materials.Bushes}
                    position={[0.315, 0.605, -0.409]}
                    rotation={[-0.146, 0, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2002.geometry}
                    material={materials.Bushes}
                    position={[-0.925, 0.61, 0.884]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush5002.geometry}
                    material={materials.Bushes_dark}
                    position={[-1.071, 0.593, 0.782]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Bush2003.geometry}
                    material={materials.Bushes_dark}
                    position={[-1.255, 0.616, 0.493]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.River_plane.geometry}
                    material={materials.Water}
                    position={[-0.635, 0.508, 0.285]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube019.geometry}
                    material={materials.Stone}
                    position={[-0.767, 0.559, 1.097]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube.geometry}
                    material={materials.Stone}
                    position={[-1.236, 0.527, -0.169]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002.geometry}
                    material={materials.Stone}
                    position={[-0.068, 0.539, 0.988]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005.geometry}
                    material={materials.Stone}
                    position={[-1.132, 0.541, -0.156]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube006.geometry}
                    material={materials.Stone}
                    position={[-0.648, 0.531, -0.494]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube008.geometry}
                    material={materials.Stone}
                    position={[-0.391, 0.512, 0.365]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube009.geometry}
                    material={materials.Stone}
                    position={[-0.829, 0.541, -0.764]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010.geometry}
                    material={materials.Stone}
                    position={[-0.081, 0.562, 1.106]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube011.geometry}
                    material={materials.Stone}
                    position={[-0.99, 0.531, 0.173]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube012.geometry}
                    material={materials.Stone}
                    position={[-0.418, 0.514, 0.29]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube013.geometry}
                    material={materials.Stone}
                    position={[-1.261, 0.531, -0.254]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube014.geometry}
                    material={materials.Stone}
                    position={[-1.06, 0.534, 0.11]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube015.geometry}
                    material={materials.Stone}
                    position={[-0.613, 0.56, -0.402]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube016.geometry}
                    material={materials.Stone}
                    position={[-0.571, 0.538, -0.288]}
                />
            </group>
        </Canvas>
    )
}

useGLTF.preload('./models/Sakura_scene_full.glb')
