/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
    OrbitControls,
    useGLTF,
    useTexture,
    shaderMaterial,
    Sparkles,
} from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas, extend, useFrame } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { LevaPanel, useControls, useCreateStore } from 'leva'

import vertexShader from './shaders/river/vertex.glsl'
import fragmentShader from './shaders/river/fragment.glsl'

const ShadedRiverMaterial = shaderMaterial(
    {
        uTime: 0,
        uEdgeColor: new THREE.Color('#dbd497'),
        uDepthColor: new THREE.Color('#23938a'),
        uDepthMap: null,
        uPerlinNoise: null,
        uFresnelColor: new THREE.Color('#ffffff'),
        uFresnelPower: 3.0,
        uFresnelStrength: 0.6,
        uFoamColor: new THREE.Color('#ffffff'),
        uFoamMin: 0.12,
        uFoamMax: 0.28,
        uFoamNoiseScale: 6.0,
        uFoamSpeed: 0.03,
        uFoamFrequency: 8.0,
        uFoamDistortion: 0.1,
        uFoamStrength: 0.8,
    },
    vertexShader,
    fragmentShader
)

extend({ ShadedRiverMaterial })

function SakuraScene() {
    const { nodes } = useGLTF('./models/Spring/Spring3.glb')
    const bakedTexture = useTexture('./models/Spring/baked.jpg')
    const depthMap = useTexture(
        './models/Spring/SpringTerrainDepthMapFixed.jpg'
    )
    const perlinNoise = useTexture('./textures/perlinNoise/perlin.png')

    // Repeat wrapping so the scaled/scrolling foam & ripple UVs tile instead of
    // clamping to a flat edge pixel
    // eslint-disable-next-line
    perlinNoise.wrapS = perlinNoise.wrapT = THREE.RepeatWrapping

    // eslint-disable-next-line
    bakedTexture.flipY = false
    // eslint-disable-next-line
    depthMap.flipY = false

    const {
        edgeColor,
        depthColor,
        fresnelColor,
        fresnelPower,
        fresnelStrength,
    } = useControls('River', {
        edgeColor: '#dbd497',
        depthColor: '#23938a',
        fresnelColor: '#ffffff',
        fresnelPower: { value: 6.0, min: 0.5, max: 10, step: 0.1 },
        fresnelStrength: { value: 0.6, min: 0, max: 1, step: 0.01 },
    })

    const {
        foamColor,
        foamMin,
        foamMax,
        foamNoiseScale,
        foamSpeed,
        foamFrequency,
        foamDistortion,
        foamStrength,
    } = useControls('Foam', {
        foamColor: '#ffffff',
        foamMin: { value: 0.31, min: 0, max: 0.5, step: 0.005 },
        foamMax: { value: 0.43, min: 0, max: 0.5, step: 0.005 },
        foamNoiseScale: { value: 6.0, min: 0.5, max: 30, step: 0.5 },
        foamSpeed: { value: 0.04, min: 0, max: 0.3, step: 0.005 },
        foamFrequency: { value: 15.0, min: 1, max: 30, step: 0.5 },
        foamDistortion: { value: 0.09, min: 0, max: 0.5, step: 0.005 },
        foamStrength: { value: 0.66, min: 0, max: 1, step: 0.01 },
    })

    const riverMaterialRef = useRef(null)

    useFrame((state, delta) => {
        if (riverMaterialRef.current) {
            riverMaterialRef.current.uTime += delta
        }
    })

    useEffect(() => {
        riverMaterialRef.current.uEdgeColor = new THREE.Color(edgeColor)
        riverMaterialRef.current.uDepthColor = new THREE.Color(depthColor)
        riverMaterialRef.current.uFresnelColor = new THREE.Color(fresnelColor)
        riverMaterialRef.current.uFresnelPower = fresnelPower
        riverMaterialRef.current.uFresnelStrength = fresnelStrength
    }, [edgeColor, depthColor, fresnelColor, fresnelPower, fresnelStrength])

    useEffect(() => {
        riverMaterialRef.current.uFoamColor = new THREE.Color(foamColor)
        riverMaterialRef.current.uFoamMin = foamMin
        riverMaterialRef.current.uFoamMax = foamMax
        riverMaterialRef.current.uFoamNoiseScale = foamNoiseScale
        riverMaterialRef.current.uFoamSpeed = foamSpeed
        riverMaterialRef.current.uFoamFrequency = foamFrequency
        riverMaterialRef.current.uFoamDistortion = foamDistortion
        riverMaterialRef.current.uFoamStrength = foamStrength
    }, [
        foamColor,
        foamMin,
        foamMax,
        foamNoiseScale,
        foamSpeed,
        foamFrequency,
        foamDistortion,
        foamStrength,
    ])

    return (
        <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
            <mesh
                geometry={nodes.merged.geometry}
                position={[-0.871, 0.616, 0.325]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
            <mesh
                geometry={nodes.river.geometry}
                position={[-0.251, 0.508, 0.127]}
            >
                <shadedRiverMaterial
                    key={ShadedRiverMaterial.key}
                    ref={riverMaterialRef}
                    uDepthMap={depthMap}
                    uPerlinNoise={perlinNoise}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Spring/Spring3.glb')

export function SpringShadedRiver() {
    const store = useCreateStore()

    return (
        <>
            <LevaPanel store={store} />

            <Canvas
                flat
                camera={{
                    fov: 45,
                    near: 0.1,
                    far: 200,
                    position: [2, 1, 2],
                }}
            >
                <color args={['#291b18']} attach="background" />
                <OrbitControls makeDefault />
                <Perf position="bottom-right" />
                <SakuraScene />
                <Sparkles
                    size={2}
                    scale={[2, 1, 2]}
                    position-y={0.7}
                    speed={0.2}
                    count={40}
                />
            </Canvas>
        </>
    )
}
