/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
    OrbitControls,
    useGLTF,
    useTexture,
    shaderMaterial,
} from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas, extend, useFrame } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'

import vertexShader from './shaders/river/vertex.glsl'
import fragmentShader from './shaders/river/fragment.glsl'
import { useControls } from 'leva'

const RiverMaterial = shaderMaterial(
    {
        uTime: 0,
        uEdgeColor: new THREE.Color('#99C460FF'),
        uDepthColor: new THREE.Color('#0e5852'),
    },
    vertexShader,
    fragmentShader
)

extend({ RiverMaterial })

function SakuraScene() {
    const { nodes } = useGLTF('./models/Spring/Spring.glb')
    const bakedTexture = useTexture('./models/Spring/baked.jpg')
    // eslint-disable-next-line
    bakedTexture.flipY = false

    const { edgeColor, depthColor } = useControls('River', {
        edgeColor: '#99C460FF',
        depthColor: '#0e5852',
    })

    const riverMaterialRef = useRef(null)

    useFrame((state, delta) => {
        if (riverMaterialRef.current) {
            riverMaterialRef.current.uTime += delta
        }
    })

    useEffect(() => {
        riverMaterialRef.current.uEdgeColor = new THREE.Color(edgeColor)
        riverMaterialRef.current.uDepthColor = new THREE.Color(depthColor)
    }, [edgeColor, depthColor])

    return (
        <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
            <mesh
                geometry={nodes.merged.geometry}
                position={[-0.871, 0.616, 0.325]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
            <mesh
                geometry={nodes.river.geometry}
                position={[-0.251, 0.508, 0.127]}
            >
                <riverMaterial key={RiverMaterial.key} ref={riverMaterialRef} />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Spring/Spring.glb')

export function SpringShadedRiver() {
    return (
        <Canvas
            flat
            camera={{
                fov: 45,
                near: 0.1,
                far: 200,
                position: [2, 1, 2],
            }}
        >
            <color args={['#291b18']} attach="background" />
            <OrbitControls makeDefault />
            <Perf />
            <SakuraScene />
        </Canvas>
    )
}
