/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
    OrbitControls,
    useGLTF,
    useTexture,
    shaderMaterial,
    Sparkles,
} from '@react-three/drei'
import { Perf } from 'r3f-perf'
import { Canvas, extend, useFrame } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { LevaPanel, useControls, useCreateStore } from 'leva'

import vertexShader from './shaders/river/vertex.glsl'
import fragmentShader from './shaders/river/fragment.glsl'

const RiverMaterial = shaderMaterial(
    {
        uTime: 0,
        uEdgeColor: new THREE.Color('#dbd497'),
        uDepthColor: new THREE.Color('#23938a'),
        uDepthMap: null,
        uPerlinNoise: null,
    },
    vertexShader,
    fragmentShader
)

extend({ RiverMaterial })

function SakuraScene() {
    const { nodes } = useGLTF('./models/Spring/Spring3.glb')
    const bakedTexture = useTexture('./models/Spring/baked.jpg')
    const depthMap = useTexture(
        './models/Spring/SpringTerrainDepthMapFixed.jpg'
    )
    const perlinNoise = useTexture('./textures/perlin.png')

    // eslint-disable-next-line
    bakedTexture.flipY = false
    // eslint-disable-next-line
    depthMap.flipY = false

    const { edgeColor, depthColor } = useControls('River', {
        edgeColor: '#dbd497',
        depthColor: '#23938a',
    })

    const riverMaterialRef = useRef(null)

    useFrame((state, delta) => {
        if (riverMaterialRef.current) {
            riverMaterialRef.current.uTime += delta
        }
    })

    useEffect(() => {
        riverMaterialRef.current.uEdgeColor = new THREE.Color(edgeColor)
        riverMaterialRef.current.uDepthColor = new THREE.Color(depthColor)
    }, [edgeColor, depthColor])

    return (
        <group rotation-y={Math.PI / 1.2} position-y={-0.5} dispose={null}>
            <mesh
                geometry={nodes.merged.geometry}
                position={[-0.871, 0.616, 0.325]}
            >
                <meshBasicMaterial map={bakedTexture} />
            </mesh>
            <mesh
                geometry={nodes.river.geometry}
                position={[-0.251, 0.508, 0.127]}
            >
                <riverMaterial
                    key={RiverMaterial.key}
                    ref={riverMaterialRef}
                    uDepthMap={depthMap}
                    uPerlinNoise={perlinNoise}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/Spring/Spring3.glb')

export function SpringShadedRiver() {
    const store = useCreateStore()

    return (
        <>
            <LevaPanel store={store} />

            <Canvas
                flat
                camera={{
                    fov: 45,
                    near: 0.1,
                    far: 200,
                    position: [2, 1, 2],
                }}
            >
                <color args={['#291b18']} attach="background" />
                <OrbitControls makeDefault />
                <Perf position="bottom-right" />
                <SakuraScene />
                <Sparkles
                    size={2}
                    scale={[2, 1, 2]}
                    position-y={0.7}
                    speed={0.2}
                    count={40}
                />
            </Canvas>
        </>
    )
}
